# Generated by Django 5.2 on 2025-06-11 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_django', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='nome',
        ),
        migrations.AddField(
            model_name='cliente',
            name='full_name',
            field=models.CharField(default='Sem nome', max_length=255),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='Sem email', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='password',
            field=models.CharField(default='Sem senha', max_length=128),
        ),
    ]
