# Generated by Django 5.2 on 2025-06-11 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_django', '0002_remove_cliente_nome_cliente_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='full_name',
            new_name='nome',
        ),
    ]
