# Generated by Django 5.2 on 2025-06-11 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_django', '0003_rename_full_name_cliente_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='telefone',
        ),
    ]
